{% set name = "qt5reactor" %}
{% set version = "0.6.2" %}
{% set sha256 = "b4533e61d883bc3e824f53bace1f91a0ae531e7eb6bf6b43e210dc9a97165e25" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - pyqt >=5
    - twisted

test:
  imports:
    - qt5reactor

about:
  home: https://github.com/sunu/qt5reactor
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Twisted Qt Integration
